version: '3.8'
services:
  db:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      - MONGODB_URI=mongodb://db:27017/registrovehicular
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data: