name: CI/CD
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd backend && npm install && npm run lint && npm test
      - run: cd frontend && npm install # si usas bundler

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/registrovehicular-backend:latest
          file: docker/Dockerfile.backend
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/registrovehicular-frontend:latest
          file: docker/Dockerfile.frontend